# Generated by Django 4.1.2 on 2023-01-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentdb',
        ),
    ]
